#!/bin/bash

YELLOW="\033[0;33m"
GREY="\033[38;5;244m"
PURPLE="\033[1;35m"
BLUE="\033[0;36m"
RED="\e[0;31m"
END="\033[0m"
FILENAME="tests_list"

printf "\n"
printf "$YELLOW"
echo "****************** MINISHELL TESTER ******************"
printf "\n"

PROMPT=$(echo -e "\nexit\n" | ./minishell | head -n 1 | sed -r "s:\x1B\[[0-9;]*[mK]::g")

i=0
while read teste
do
	((i++))
	MINI_OUTPUT=$(echo "$teste" | ./minishell 2> /dev/null | sed -r "s:\x1B\[[0-9;]*[mK]::g" | grep -v "$PROMPT" | grep -v ^exit$ )
	MINI_EXIT_CODE=$(echo -e "./minishell\n$teste\necho \$?\nexit\n" | ./minishell 2> /dev/null | sed -r "s:\x1B\[[0-9;]*[mK]::g" | grep -v "$PROMPT" | grep -v ^exit$ | tail -n 1)
	MINI_ERROR_MSG=$(echo "$teste" | ./minishell 2>&1 > /dev/null | grep -o '[^:]*$' | xargs)

	BASH_OUTPUT=$(bash -c "$teste" 2> /dev/null)
	BASH_EXIT_CODE=$(echo $?)
	BASH_ERROR_MSG=$(bash -c "$teste" 2>&1 > /dev/null | grep -o '[^:]*$' | xargs)

	printf "$BLUE"
	printf "Test %3s: " $i
	if [[ "$MINI_OUTPUT" == "$BASH_OUTPUT" && "$MINI_EXIT_CODE" == "$BASH_EXIT_CODE" && "$MINI_ERROR_MSG" == "$BASH_ERROR_MSG" ]]; then
		printf ✅
		((ok++))
	else
		printf ❌
	fi
	printf "$GREY $teste \n$END"
	if [ "$MINI_OUTPUT" != "$BASH_OUTPUT" ]; then
		echo mini output = \($MINI_OUTPUT\)
		echo bash output = \($BASH_OUTPUT\)
	fi
	if [ "$MINI_EXIT_CODE" != "$BASH_EXIT_CODE" ]; then
		echo mini exit code = $MINI_EXIT_CODE
		echo bash exit code = $BASH_EXIT_CODE
	fi
	if [ "$MINI_ERROR_MSG" != "$BASH_ERROR_MSG" ]; then
		echo mini error = $MINI_ERROR_MSG
		echo bash error = $BASH_ERROR_MSG
	fi
	# echo -e "________________________________________________________________\n"
done < tests/$FILENAME

printf $PURPLE
printf "$ok/$i\n"
if [[ "$ok" == "$i" ]]; then
	echo "🎊 🎊 🎊"
	echo "😎 😎 😎"
	echo "🎉 🎉 🎉"
else
	echo "😭 😭 😭"
fi
printf $END
