name: Make Test CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make
    - name: Clone tester
      run: git clone https://github.com/LucasKuhn/minishell_tester.git
    - name: Run tests
      run: make test
